name = "Greg's Factory II"
author = "Annwan, LunaFrejya"
version = "b.4.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bdd18a5ef41b02c928b174709c96777a56c1110890331a79b930c6a41250f85"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
