name = "Qilby Industries"
author = "Annwan, LunaFrejya"
version = "b.4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcadec8404f13dbecdba8716d02d4b1c215f8dcec5f0d35cf42719f522777505"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
