name = "Greg's Factory II"
author = "Annwan, LunaFrejya"
version = "b.4.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c85d6b6b7dd00080d3adf1c9d3728151f8d6d3db8574e5e897b473617ab4a89"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
