name = "Greg's Factory II"
author = "Annwan, LunaFrejya"
version = "b.4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2fe98cc61022604424ab0a3dcd1eabf6ba505c0cf510a707c33ca78e1964563"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
