name = "Greg's Factory II"
author = "Annwan, LunaFrejya"
version = "b.3.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64618a61bf6ad97aaf93fbca248914a8ed6987075f33a780167f718054ce8642"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
