name = "Greg's Factory II"
author = "Annwan, LunaFrejya"
version = "b.3.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebbb5d393f3276ad5810ff7a2041ddfb0719d15eb1ee5e063ab307ceb2e7523e"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
