name = "Qilby Industries"
author = "Annwan, LunaFrejya"
version = "b.4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99bdfe79893ce3dbdb8d0cb1e382eed9ea3eb037864ced390a54113e4872d3ea"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
